name: Deploy

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/book_project_key
          chmod 600 ~/.ssh/book_project_key

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/book_project_key -o StrictHostKeyChecking=no      $SSH_USER@$SSH_HOST << 'EOF'
            cd /home/ubuntu/fastapi-book-project
            git fetch origin main
            git reset --hard origin/main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi
          EOF
