name: Deploy

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/book_project_key
          chmod 600 ~/.ssh/book_project_key
          ssh -i ~/.ssh/book_project_key -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            cd /home/ubuntu/fastapi-book-project
            git pull --rebase origin main
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            sudo systemctl restart fastapi
          EOF
